variables:
  KAFKA_CONFIG: '{
  "auto.offset.reset": "smallest",
  "bootstrap.servers": "spine.ntex.com:10180",
  "client.id": "er-frappe-docker",
  "default.topic.config": {
   "acks": "all"
  },
  "fetch.message.max.bytes": "81920",
  "group.id": "er-frappe-docker-spine-client",
  "request.required.acks": "1"
 }'
dev-erfrappe-deploy:
  stage: deploy
  script:
    - pwd
    - ./build-frappe11.sh develop
    - docker push dock.elasticrun.in/er-frappe11-base:develop
  only:
    - develop
    - master
  tags:
    - build-srv


beta-erfrappe-deploy:
  stage: deploy
  script:
    - pwd
    - ./build-frappe11.sh beta-release
    - docker push dock.elasticrun.in/er-frappe11-base:beta-release
  only:
    - beta-release
  tags:
    - build-srv
    - beta

prod-erfrappe-deploy:
  stage: deploy
  script:
    - pwd
    - ./build-frappe11.sh release
    - docker push dock.elasticrun.in/er-frappe11-base:release
    - docker push dock.elasticrun.in/er-frappe11-base:${CI_COMMIT_SHORT_SHA}
  only:
    - release
    - prod
  tags:
    - prod
    - release
