dev-erfrappe-deploy:
  stage: deploy
  script:
    - pwd
    - ./build-frappe10.sh dev
    - ./build-frappe11.sh dev
    - docker push dock.elasticrun.in/er-frappe10-base:dev
    - docker push dock.elasticrun.in/er-frappe11-base:dev
  only:
    - dev
    - master
  tags:
    - local
    - dev

    
beta-cas-deploy:
  stage: deploy
  script:
    - pwd
    - ./build-frappe10.sh beta
    - ./build-frappe11.sh beta
    - docker push dock.elasticrun.in/er-frappe10-base:beta
    - docker push dock.elasticrun.in/er-frappe11-base:beta
  only:
    - beta-release
  tags:
    - build-srv 
    - beta 

prod-cas-deploy:
  stage: deploy
  script:
    - pwd
    - ./build-frappe10.sh release
    - ./build-frappe11.sh release
    - docker push dock.elasticrun.in/er-frappe10-base:release
    - docker push dock.elasticrun.in/er-frappe11-base:release
  only:
    - release
    - prod
  tags:
    - prod
    - release 
