kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: er-frappe-sites-sc
# labels:
#     addonmanager.kubernetes.io/mode: EnsureExists
reclaimPolicy: Retain
allowVolumeExpansion: true
# mountOptions:
#   - dir_mode=0777
#   - file_mode=0777
#   - uid=frappe
#   - gid=frappe
# Values below are specific to provider
provisioner: microk8s.io/hostpath

