apiVersion: v1
kind: Secret
metadata:
  name: trun-frappe-mariadb-secrets
data:
  # Base64 encoded host name mariadb - created by the service.
  db.host: bWFyaWFkYg==
  # Base64 encoded DB Name to be used for site. (tredrundb-k8s)
  db.name: dHJlZHJ1bmRiLWs4cw==
  # DB Password - password
  db.password: cGFzc3dvcmQ=
  # Admin password for frappe site - admin
  admin.password: cGFzc3dvcmQ=
