apiVersion: apps/v1
kind: Deployment
metadata:
  name: er-redisq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: er-redisq
  template:
    metadata:
      labels:
        app: er-redisq
    spec:
      containers:
      # Local redis queue in the pod.
      - name: redis-queue
        image: redis:alpine
        command: ["redis-server","/etc/conf.d/redis_queue.conf"]
        resources: {}
          # limits:
          #   memory: "256Mi"
          #   cpu: "100m"
        ports:
          - containerPort: 11000
        volumeMounts:
        - mountPath: /etc/conf.d
          name: er-frappe-redis-queue-config
      restartPolicy: Always
      volumes:
      - name : er-frappe-redis-queue-config
        configMap:
          name: er-frappe-redis-config
          items:
          - key: redis_queue.conf
            path: redis_queue.conf
