apiVersion: v1
kind: ConfigMap
metadata:
  name: er-frappe-fluentd-config
data:
  fluent.conf: |
    <source>
    @type tail
    path /fluentd/log/*.log
    pos_file /home/frappe/td-agent/frappe-logs.pos
    tag frappe.${file}
    <parse>
      @type none
    </parse>
    </source>
    <match frappe>
      @type elasticsearch
      host frappe.elk.ntex.com
      port 9200
      logstash_format true
    </match>
