apiVersion: v1
kind: ConfigMap
metadata:
  name: trun-frappe-fluent-config
data:
  fluent.conf: |
    <source>
    @type tail
    path /home/frappe/*/logs/*.log
    pos_file /home/frappe/td-agent/frappe-logs.pos
    tag frappe.${file}
    <parse>
      @type none
    </parse>
    </source>
    <match frappe>
      @type elasticsearch
      host elasticsearch-host
      port 9200
      logstash_format true
    </match>
