version: '2'
services:
  mariadb:
    image: mariadb:10.3
    environment:
      - MYSQL_ROOT_PASSWORD=ntex@123
      - MYSQL_USER=root
    volumes:
      - ./conf/mariadb-conf.d:/etc/mysql/conf.d:ro
      - ./mariadb_data:/var/lib/mysql:rw
    user:
      mysql
    ports:
      - "3307:3306" #mariadb-port
    container_name: frappe11-local-db-ntex-com
#  volumes:
#    mariadb_data:
#      external: true

  redis-cache:
    image: redis:alpine
    volumes:
      - ./redis-conf:/etc/conf.d
    command: ["redis-server","/etc/conf.d/redis_cache.conf"]
    container_name: redis-cache

  redis-bigcache:
    image: redis:alpine
    volumes:
      - ./redis-conf:/etc/conf.d
    command: ["redis-server","/etc/conf.d/redis_bigcache.conf"]
    container_name: redis-bigcache

  redis-queue:
    image: redis:alpine
    volumes:
      - ./redis-conf:/etc/conf.d
    command: ["redis-server","/etc/conf.d/redis_queue.conf"]
    container_name: redis-queue

  redis-socketio:
    image: redis:alpine
    volumes:
      - ./redis-conf:/etc/conf.d
    command: ["redis-server","/etc/conf.d/redis_socketio.conf"]
    container_name: redis-socketio

  frappe:
    image: dock.elasticrun.in/er-frappe11-base:develop-xenial
    volumes:
      - ./env:/home/frappe/docker-bench/config/env
      - ./logs:/home/frappe/docker-bench/logs
      - ./sites/site1.docker:/home/frappe/docker-bench/sites/site1.docker
      - ./currentsite.txt:/home/frappe/docker-bench/sites/currentsite.txt
      - ./apps.txt:/home/frappe/docker-bench/sites/apps.txt
      - ./common_site_config.json:/home/frappe/docker-bench/sites/common_site_config.json
    environment: 
      - GUNI_WORKER_CONNECTIONS=10
      - GUNI_WORKERS=1
      - DB_NAME=frappe11localdb
      - DB_PASSWORD=ntex@123
      - ADMIN_PASSWORD=password
      - RELEASE_NAME=frappe11-local
    ports:
      - "8888:8000" #webserver_port
    stdin_open: true
    tty: true
    links:
      - redis-cache
      - redis-queue
      - redis-socketio
      - redis-bigcache
      - mariadb
    depends_on:
      - mariadb
      - redis-cache
      - redis-bigcache
      - redis-queue
      - redis-socketio
    container_name: er-frappe
